server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Map .gif sprites to the showdown animated sprite folder
    location ~ ^/pkmn/back/(\d+)\.gif$ {
        alias /usr/share/nginx/html/sprites-master/sprites/pokemon/other/showdown/back/$1.gif;
    }
    
    location ~ ^/pkmn/(\d+)\.gif$ {
        alias /usr/share/nginx/html/sprites-master/sprites/pokemon/other/showdown/$1.gif;
    }

    # Map .png sprites to the static sprite folder
    location /pkmn/ {
        alias /usr/share/nginx/html/sprites-master/sprites/pokemon/;
    }

    location /api/ {
        # The backend service will be named 'backend' in docker-compose
        proxy_pass http://backend:3001/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
