// One-time generator: fetches the National Dex from PokeAPI and writes our data tables.
// Run: node scripts/gen-data.mjs
import { writeFileSync } from 'node:fs';

const MAX = 1025;
const GROWTH = { 'slow': 'slow', 'medium': 'mediumfast', 'fast': 'fast',
  'medium-slow': 'mediumslow', 'slow-then-very-fast': 'erratic', 'fast-then-very-slow': 'fluctuating' };
const STAT = { 'hp': 'hp', 'attack': 'atk', 'defense': 'def', 'special-attack': 'spa', 'special-defense': 'spd', 'speed': 'spe' };
const toKey = (n) => n.toLowerCase().replace(/[^a-z0-9]/g, '');

async function getJson(url) { const r = await fetch(url); if (!r.ok) throw new Error(url + ' ' + r.status); return r.json(); }

async function fetchOne(num) {
  const [sp, pk] = await Promise.all([
    getJson(`https://pokeapi.co/api/v2/pokemon-species/${num}`),
    getJson(`https://pokeapi.co/api/v2/pokemon/${num}`),
  ]);
  const key = toKey(sp.name);
  const ev = { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 };
  for (const s of pk.stats) ev[STAT[s.stat.name]] = s.effort;
  return { key, catch: sp.capture_rate, exp: pk.base_experience ?? 100, growth: GROWTH[sp.growth_rate.name] ?? 'mediumfast', ev };
}

async function pool(nums, size, fn) {
  const out = []; let i = 0;
  async function worker() { while (i < nums.length) { const n = nums[i++]; try { out.push(await fn(n)); } catch (e) { console.error('skip', n, e.message); } } }
  await Promise.all(Array.from({ length: size }, worker));
  return out;
}

const rows = (await pool([...Array(MAX)].map((_, i) => i + 1), 12, fetchOne)).sort((a, b) => a.key.localeCompare(b.key));
const obj = (pairs) => '{\n' + pairs.map(([k, v]) => `  "${k}": ${v},`).join('\n') + '\n}';

writeFileSync('src/data/catch-rates.ts',
`// GENERATED by scripts/gen-data.mjs from PokeAPI. Do not edit by hand.
import { toKey } from './normalize';
export const CATCH_RATES: Record<string, number> = ${obj(rows.map(r => [r.key, r.catch]))};
export function baseCatchRate(speciesId: string): number { return CATCH_RATES[toKey(speciesId)] ?? 45; }
`);

writeFileSync('src/game/exp-yield.ts',
`// GENERATED by scripts/gen-data.mjs from PokeAPI. Do not edit by hand.
import { toKey } from '../data/normalize';
export const EXP_YIELD: Record<string, number> = ${obj(rows.map(r => [r.key, r.exp]))};
export function baseExpYield(species: string): number { return EXP_YIELD[toKey(species)] ?? 100; }
`);

writeFileSync('src/game/growth-rates.ts',
`// GENERATED by scripts/gen-data.mjs from PokeAPI. Do not edit by hand.
import { toKey } from '../data/normalize';
export type GrowthGroup = 'fast' | 'mediumfast' | 'mediumslow' | 'slow' | 'erratic' | 'fluctuating';
export function expForLevel(level: number, group: GrowthGroup): number {
  const n = level; if (n <= 1) return 0;
  switch (group) {
    case 'fast': return Math.floor((4 * n ** 3) / 5);
    case 'mediumfast': return n ** 3;
    case 'mediumslow': return Math.floor((6 / 5) * n ** 3 - 15 * n ** 2 + 100 * n - 140);
    case 'slow': return Math.floor((5 * n ** 3) / 4);
    case 'erratic':
      if (n < 50) return Math.floor((n ** 3 * (100 - n)) / 50);
      if (n < 68) return Math.floor((n ** 3 * (150 - n)) / 100);
      if (n < 98) return Math.floor((n ** 3 * Math.floor((1911 - 10 * n) / 3)) / 500);
      return Math.floor((n ** 3 * (160 - n)) / 100);
    case 'fluctuating':
      if (n < 15) return Math.floor((n ** 3 * (Math.floor((n + 1) / 3) + 24)) / 50);
      if (n < 36) return Math.floor((n ** 3 * (n + 14)) / 50);
      return Math.floor((n ** 3 * (Math.floor(n / 2) + 32)) / 50);
  }
}
export const GROUPS: Record<string, GrowthGroup> = ${obj(rows.map(r => [r.key, `'${r.growth}'`]))};
export function growthRateOf(species: string): GrowthGroup { return GROUPS[toKey(species)] ?? 'mediumfast'; }
`);

writeFileSync('src/data/ev-yield.ts',
`// GENERATED by scripts/gen-data.mjs from PokeAPI. Do not edit by hand.
import { toKey } from './normalize';
export interface Ev6 { hp: number; atk: number; def: number; spa: number; spd: number; spe: number; }
export const EV_YIELD: Record<string, Ev6> = ${obj(rows.map(r => [r.key, `{ hp: ${r.ev.hp}, atk: ${r.ev.atk}, def: ${r.ev.def}, spa: ${r.ev.spa}, spd: ${r.ev.spd}, spe: ${r.ev.spe} }`]))};
export function evYield(species: string): Ev6 { return EV_YIELD[toKey(species)] ?? { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }; }
`);

console.log('generated', rows.length, 'species');
